# __Attributes and Functions in Python__

## __Agenda__

- Attributes of NumPy Arrays
  * Explanation of Attributes
- NumPy Array Functions

## __1. Attributes of NumPy Arrays__ ##

A few commonly used attributes of NumPy array include:

![image.png](attachment:55bef5b9-d8e7-4375-b30f-5f7160f4685f.png)

In [ ]:
# An example for each attribute is given below:
import numpy as np
arr = np.array([[ 1, 2, 3], [ 4, 2, 5]])
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
print("Length of one array element in bytes. : ", arr.itemsize)
print("array’s data. : ", arr.data)

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64
Length of one array element in bytes. :  8
array’s data. :  <memory at 0x7f3e637b6cf0>


### __1.1 Explanation of Attributes:__ ###
- `ndarray.ndim`: It is the number of axes (dimensions) of the array.
![image.png](attachment:4da7dd4b-8f51-4c1c-8a8e-6ddfbb2d1d57.png)
- `ndarray.shape`: It provides the size of the array for each dimension. The output data type is a tuple.
![image.png](attachment:959ced9c-f1e8-4e61-a57e-e1978d321e2b.png)
- `ndarray.size` : It is the total number of elements in the array.
![image.png](attachment:dbafacca-f7b2-4051-83e5-7477de83fe64.png)
- `ndarray.dtype`: It shows the data type of the elements in the array.
![image.png](attachment:7b6b5f2e-12ce-4a10-92f9-ad898f4cb9f6.png)
- `ndarray.itemsize`: It shows the length of one array element in bytes.
![image.png](attachment:1179ad2e-d2a8-4687-b9d5-0b6d4e1a1238.png)![image.png](attachment:4a0d7f58-654b-4eb6-a370-82d9d5007193.png)
- `ndarray.data`: It is an attribute offering direct access to the raw memory of a NumPy array.

## __2. NumPy Array Functions__ ##
![image.png](attachment:86c7dd60-f70e-401d-891c-5eada1aa52fe.png)

- `ndarray.reshape`: It returns an array containing the same data with a new shape.

In [ ]:
# Example: Converting a 1D Array to a 2D Array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print (newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


- `ndarray.flatten`: It returns a copy of the array flattened into a 1D array.

In [ ]:
# Converting a multidimensional(3D) array into a 1D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = arr3D.flatten()
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- `ndarray.transpose`: It swaps the rows and columns of a 2D array.

In [ ]:
# Let's create a 2D array for the transpose example
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
# Transposing the 2D array
transposed_array = arr2D.transpose()
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])