# __Indexing__

## __Agenda__

- NumPy Array Indexing
  * Access 1D NumPy Array Elements
  * Access 2D NumPy Array Elements
  * Access 3D NumPy Array Elements
  * Negative Indexing

## __1. NumPy Array Indexing__ ##
NumPy indexing lets you access an array element with an index value, starting from 0.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [1]:
# Creating 1D, 2D, and 3D NumPy arrays
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

The above code creates 1D, 2D, and 3D NumPy arrays with specified elements, providing structured data representations for different dimensions.

### __1.1 Access 1D NumPy Array Elements__ ###

In [2]:
# Print the value at index 3 of the 1D NumPy array
print(array_1d[3])

4


The above code prints the value located at index 3 of a one-dimensional NumPy array.

In [3]:
# Print the sum of the values at indexes 0 and 1 in the 1D NumPy array
print(array_1d[1] + array_1d[0])

3


The above code calculates the sum of the values at the first and second indexes of a one-dimensional NumPy array.

### __1.2 Access 2D NumPy Array Elements__
Consider a 2D array as a table, with dimensions representing rows and indexes representing columns.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [4]:
# Printing the third element in the first row of the 2D array
print('Third element in the first row: ', array_2d[0, 2])

Third element in the first row:  3


The above code prints the value located in the first row and third column of a two-dimensional array.

In [5]:
# Printing the second element in the second row of the 2D array
print('Second element in the second row: ', array_2d[1, 1])

Second element in the second row:  5


The above code prints the value located in the second row and second column of a two-dimensional array.

In [ ]:
# Print the 3D NumPy array
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


The above code prints a 3D NumPy array. The output displays the array's elements organized in a cube-like structure, representing data arranged across three dimensions.

### __1.3 Access 3D NumPy Array Elements__ ###
- [x, y, z] corresponds to the xth element, yth row, and zth column.

In [ ]:
# Print the first element of the first row of the second 2D array within the 3D array
print(array_3d[1, 0, 0])

7


The above code prints the value located in the first row and first column of the first matrix within the second set of matrices.

### __1.4 Negative Indexing__

- Negative indices count backward from the end of the array.
- In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [ ]:
# Printing the fourth element from the end of the 1D array using negative indexing
print(array_1d[-3])

4


The above code prints the fourth element from the end of a 1D array. Negative indexing counts elements from the end.

In [ ]:
# Printing the last element in the second row of the 2D array using negative indexing
print(array_2d[1, -1])

6


The above code prints the last element in the second row of a 2D array.

In [ ]:
# Printing the last element in the last row of the last 2D array within the 3D array using negative indexing
print(array_3d[1, 1, -1])

12


The above code prints the last element in the last row of the last 2D array within the 3D array using negative indexing.

## __Assisted Practice__

### __Problem Statement:__

1. Create a one-dimensional NumPy array containing at least ten elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval
5. Access and print various elements from 1D, 2D, and 3D arrays using positive indexing
6. Perform and print some basic arithmetic operations (like addition or  subtraction) using elements accessed from 1D, 2D, and 3D arrays
7. Access and print elements using negative indices in all three arrays